### ISSUE TITLE
Getting exception `configuration must contain projectId`

### ISSUE THREAD

**Issue by ezekielaquino** [bundlesandbatches/next-sanity-image#1]
Using a very basic configuration, I get an exception `configuration must contain projectId`. see below for usage. absolutely certain that the instantiated `sanityClient` is working since all my groq queries are fine. Is there anything that I might be missing?

sanity/client 2.1.4
next 10.0.5

```js
// Image wrapper
import Img from 'next/image';
import {useNextSanityImage} from 'next-sanity-image';
import sanityClient from '@/services/sanityClient';

const Image = ({src}) => {
  const imageProps = useNextSanityImage(sanityClient, src);

  return <Img {...imageProps} />;
};

export default Image;
```

**Comment by ezekielaquino** [comment]
edit: I added `@sanity/image-url` and updated it 0.140.19, and the error changed to ` Cannot read property 'split' of undefined` coming from the hook 🤔

**Comment by lorenzodejong** [comment]
Thanks for opening this issue. From the looks of it this has to do with instantiating `SanityClient`. I'm not sure if this has anything to do specifically with this library. The specific error occurs from the following line:
https://github.com/sanity-io/sanity/blob/a3f7158016d63728a9b435e6ab444ff2b90fd424/packages/%40sanity/client/src/config.js#L56. Could you confirm that this is the case from your error logs?

This library only passes the `SanityClient` instance to `@sanity/image-url`, and even has `@sanity/client` as a peer dependency so it should not be in the way of your own dependency versioning. Does the issue only occur when having `next-sanity-image` installed?

**Comment by lorenzodejong** [comment]
Closed due to inactivity.

**Comment by quitequinn** [comment]
Was there a solution found for this @ezekielaquino ?

**Comment by Abdulmuneebswati** [comment]
quitequinn have you found solution?

**Comment by ethandunford** [comment]
I'm now receiving error when visiting some pages.

Configuration
```
const client = createClient({
  projectId: process.env.SANITY_PROJECT_ID,
  dataset: process.env.SANITY_DATA_SET,
  apiVersion: "2022-03-25",
  useCdn: false
```

npm: 8.11.0
node: v16.15.1:
next-sanity": "^4.1.1",

**Comment by quitequinn** [comment]
I did.. but I think it was something silly like I had the wrong character in the .env or something like that. Make sure your environmental variables are being loaded in correctly!

**Comment by briandev25** [comment]
when saving a variable on .env file
VARIABLE_NAME(space) = (space) variable 
Otherwise without the space it generates this error

**Comment by mishraji900** [comment]
import { SanityClient } from '@sanity/client';
import {imageUrlBuilder} from '@sanity/image-url';

export const client = new SanityClient({
  projectId: process.env.ReactTokenId,
  dataset: 'production',
  apiVersion: '2023-07-04',
  useCdn: true,
  token: process.env.ReactTokenId,
});

const builder = imageUrlBuilder(client);

export const urlFor = (source) => builder.image(source);
why is this not running

**Comment by dev-bello** [comment]
> 

have you found a solution yet? that is the same error I am also dealing with

**Comment by lorenzodejong** [comment]
@mishraji900 does it work when you expicitly provide the `projectId` and `token` properties to your `SanityClient` instance? If that's the case, it might have something to do with your environment variables. If you're making this call from the client-side, the `projectId` environment variable should be present. However i would not recommend to expose your token on the client-side.

Besides that check which version of `@sanity/client` and `next-sanity-image` you're running. Make sure to check for compatibility in the `peerDependencies` of the package.json: https://github.com/lorenzodejong/next-sanity-image/blob/main/package.json.

**Comment by MihailoMilic** [comment]
@lorenzodejong  

import { SanityClient } from '@sanity/client'
import imageUrlBuilder from '@sanity/image-url'

export const client = new SanityClient({
    projectId : 'z2ptzyq6',
    dataset : 'production',
    apiVersion: '2023-7-26',
    useCdn: true,
    token: 'sk2v5YoYB5yatNa46F8GwhxfnRWzR5BvuLJSZe2vnw26nLl5mREpcHW9VCkXCL3qv9iX5JPANxjZ2kcclDZCyi3SfCcprnoFFXpuLzRDOQNcKgLJVZpLcwmWRh8wRyYVJGjWNCBXDDJMnDKw1xtFjZ4s3W1xZTcvD9PFTBhFzGm1OKEdzeMU'
}
)

const builder = imageUrlBuilder(client);

export const urlFor = (source) => builder.image(source);

This is my code, I am still experiencing the error:

Configuration must contain `projectId`

**Comment by GTANSOLDIER** [comment]
Go to **sanity.config.js** and input your projectId

projectId: 'projectId',

This worked for me

**Comment by Vagdevi-yalla** [comment]
Configuration must contain `projectId`
i have checked all the above methods but this issue still persists
