### ISSUE TITLE
Add support for NextJS blurred image placeholder

### ISSUE THREAD

**Issue by wrux** [bundlesandbatches/next-sanity-image#10]
NextJS 11 released with a new burred placeholder feature. The `@sanity/image-url` package already has support for blurred images, so it would be awesome to implement the feature in the `next-sanity-image` package.

Links:

- [@sanity/next-image-url docs](https://www.sanity.io/docs/image-url#bluramount)
- [NextJS 11 placeholders](https://nextjs.org/blog/next-11#image-placeholders)

**Comment by lorenzodejong** [comment]
Yesterday i've watched the Next.js conference and noticed they've added support for this. I was planning to get this integrated today, thanks for the heads up. Will let you know when there's a new version available!

**Comment by lorenzodejong** [comment]
Version 3.1.0 has just been shipped including blur-up image support and (optional) image transformations. If there are any issues please let me know!

**Comment by surjithctly** [comment]
@lorenzodejong Does that make use of lqip or blurha.sh ? 

Blurhash looks more polished than lqip.

**Comment by lorenzodejong** [comment]
@surjithctly neither, it uses the built-in options from @sanity/image-url which directly passes the option to the Sanity CDN (which does all of the image transformations, caching, etc. for us). Basically i'm adjusting the width/height of the image to a very low amount and applying blur to the image: https://www.sanity.io/docs/image-url#bluramount
