### ISSUE TITLE
Need a solution when the image object is empty

### ISSUE THREAD

**Issue by giacomoalonzi** [bundlesandbatches/next-sanity-image#12]
Hello, thanks for your work, but I noticed when the "image" object is empty javascript crashes.
Eg. I have a Hero component that it should have or not the image. How can I handle it? Thanks.

**Comment by lorenzodejong** [comment]
I've just released version 3.1.3 which should fix this issue, the image parameter can now be set to `null` which in turn sets the return value of the hook to `null`.

**Comment by giacomoalonzi** [comment]
I'm still having
Unhandled Runtime Error
TypeError: Cannot read property 'split' of undefined

![image](https://user-images.githubusercontent.com/16420302/124610464-d4a1a980-de70-11eb-969b-d0c3395377c2.png)

I've tried to pass undefined or null but the result is the same.
I've updated to the latest version and deleted all modules and cleaned the cache. No luck!

Thanks for your help!
