### ISSUE TITLE
Bundle image as static asset

### ISSUE THREAD

**Issue by darbio** [bundlesandbatches/next-sanity-image#2]
Is there a way to download the static image and bundle it into the build assets? I would like to bundle my static assets in with my website when I build it and deploy to a static host (s3). 

Currently I can reference images by the Sanity CDN but I'd rather these are on my own URL rather than the Sanity CDN.

**Comment by lorenzodejong** [comment]
Hey darbio, thanks for opening an issue. This library is specifically aimed towards using images from the Sanity CDN in a responsive manner. However i noticed there's another library which also supports downloading images from a CDN to the local filesystem: https://github.com/twopluszero/next-images. The source code from both this and next-images is fairly minimal, perhaps you can combine these to something that fits your requirements.
