### ISSUE TITLE
Hotspots and Crops not respected

### ISSUE THREAD

**Issue by 1jmj** [bundlesandbatches/next-sanity-image#22]
If  you have hotspots set or image is cropped using Sanity's built in tools, it's not respected with next-sanity-image.  There should be a way to either automatically or via a prop use any crop or hotspots set by the Sanity user.

example schema:

```
import { FaRegImage } from "react-icons/fa";
export default {
  name: "figure",
  title: "Image",
  type: "image",
  options: {
    hotspot: true,   // if this is set to true, user can set hotspots and crop the image, so their selected preference should follow to display
    metadata: ["lqip"],
  },
  icon: FaRegImage,
  fields: [
    {
      name: "alt",
      type: "string",
      title: "Alternative text",
      description: "Important for SEO and accessibility. Describe the image",
      options: {
        isHighlighted: true,
      },
      validation: (Rule) => [Rule.required().error("You need to set Alt text")],
    },
  ],
  preview: {
    select: {
      imageUrl: "asset.url",
      title: "alt",
    },
  },
};

```

**Comment by gpoole** [comment]
@lorenzodejong in my case I've found that the crop is being applied correctly to the image itself, but the aspect ratio for the dimensions returned for cropped images is not correct. I think that `useNextSanityImage` may need to apply the crop to the width and height it returns for `layout="responsive"` and `layout="instrinsic"` to work correctly with next/image? I've found that the following works as expected for me:

```jsx
const imageProps = useNextSanityImage(getSanityClient(), image)

if (image.crop) {
  imageProps.width *= 1 - (image.crop.left + image.crop.right)
  imageProps.height *= 1 - (image.crop.top + image.crop.bottom)
}
```

Does that sound right to you? I'm happy to open a PR to add that.

I've also found that the hotspot doesn't seem to be being applied as I expected and I can't see it being included in the URL, but haven't looked into it closely yet.

**Comment by 1jmj** [comment]
^ this sounds like the issue I had. Sorry I don’t have the original code to reproduce the issue. The project was urgent and all completed another way now.

**Comment by lorenzodejong** [comment]
@gpoole feel free to open a PR for this! I think the proposed solution would probably work fine, we'll have to test any of the possible edge cases with this implementation.

**Comment by cspui** [comment]
For anyone stumble on how to use the hotspot feature
Here is the code for imageBuilder to fetch the respective hotspot image:

`
useNextSanityImage(client, imageProps, {
    imageBuilder:  (imageUrlBuilder, options) => {
          if (
            isShowHotspot &&
            imageProps.hotspot &&
            imageProps.hotspot.width &&
            imageProps.hotspot.height &&
            imageProps.hotspot.x &&
            imageProps.hotspot.y
          ) {
            const width = options.originalImageDimensions.width;
            const height = options.originalImageDimensions.height;
            const hotspotWidthPercentage = imageProps.hotspot.width;
            const hotspotHeightPercentage = imageProps.hotspot.height;
            const hotspotCenterXPercentage = imageProps.hotspot.x;
            const hotspotCenterYPercentage = imageProps.hotspot.y;

            const left = (hotspotCenterXPercentage - hotspotWidthPercentage / 2) * width;
            const top = (hotspotCenterYPercentage - hotspotHeightPercentage / 2) * height;

            // round the values to the nearest pixel
            const roundedLeft = Math.round(left);
            const roundedTop = Math.round(top);
            const roundedWidth = Math.round(hotspotWidthPercentage * width);
            const roundedHeight = Math.round(hotspotHeightPercentage * height);

            return imageUrlBuilder
              .rect(roundedLeft, roundedTop, roundedWidth, roundedHeight)
              .quality(100);
          }

          return imageUrlBuilder.quality(100);
        },
  });
  `
