### ISSUE TITLE
Problems processing multiple urls in the same component

### ISSUE THREAD

**Issue by michael-odonovan** [bundlesandbatches/next-sanity-image#28]
Hi,
Thanks for your work on the plugin : )
I'm trying to process a bunch of "product" images and came up with this function:
```
  function imageProps(i, imgNumber) {
    return useNextSanityImage(
        sanityClient,
        products[i].[imgNumber]
      )
  }
```
however when I try to call it more than once in the component I get this error:
Unhandled Runtime Error
```
Error: Rendered more hooks than during the previous render.
Source

components/ProductSliders.js (11:8) @ imageProps

   9 | function imageProps(i, imgNumber) {
  10 |   return useNextSanityImage(
> 11 |       sanityClient,
     |      ^
  12 |       products[i].[imgNumber]
  13 |     )
  14 | }
```
Your help much appreciated.

**Comment by lorenzodejong** [comment]
I'm guessing you're breaking the rules of hooks by rendering the hook in a loop (judging from the index you're passing): https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level.

> **Don’t call Hooks inside loops, conditions, or nested functions.** Instead, always use Hooks at the top level of your React function, before any early returns.
