### ISSUE TITLE
Accidental debug statement

### ISSUE THREAD

**Issue by leeuwd** [bundlesandbatches/next-sanity-image#29]
Did an accidental debug statement slip into the `next-sanity-image@3.2.0` codebase?

![image](https://user-images.githubusercontent.com/1755190/143418059-49a9e070-a38a-4b89-89fe-067c4f65b9fc.png)
![image](https://user-images.githubusercontent.com/1755190/143418284-7c169236-422f-431a-a4bc-cdf3f91a6b1c.png)

I've reinstalled all our modules to exclude any `console.log()` statements written in `node_modules/*.*`.

**Comment by lorenzodejong** [comment]
Correct, this was accidentally included by my mistake. Version 3.2.1 should fix this.
