### ISSUE TITLE
Update to work with Next 12 and image transformations

### ISSUE THREAD

**Issue by wenche** [bundlesandbatches/next-sanity-image#31]
👋 

[The fix for Next 12](https://github.com/bundlesandbatches/next-sanity-image/issues/23) does not remove all the warnings. If you use image transformations, you'll still see a lot of warnings because the imageBuilder returns a `w` instead of a `width` parameter.

We've discussed this with Sanity, and they suggest to manually add the width as a workaround that satisfies both Next.js and doesn't effect the image from Sanity. 

![Screenshot 2021-12-01 at 14 53 23](https://user-images.githubusercontent.com/1568252/144412300-7ec77fcb-31a6-4c0d-b66c-363a8098e421.png)

**Comment by lorenzodejong** [comment]
This warning does not seem to occur anymore in my test cases using any version of Next.js 12.x. Could you perhaps provide a reproducible test case so we can see if we can solve this issue?
