### ISSUE TITLE
Erronous placeholder type!

### ISSUE THREAD

**Issue by jonjohansen** [bundlesandbatches/next-sanity-image#33]
Hi!

Ran into an issue when using this library with the type definition for `placeholder` which doesn't match up with the one in `next/image`. According to their doc it isn't a string, but instead `'blur' | 'empty' | undefined`. 

I put in a workaround with a typeguard in my project, but i figured i'd let you know.

https://github.com/bundlesandbatches/next-sanity-image/blob/cfb99cfa8f9cfd993e1f4c07bcd5667b09826ddf/src/types.ts#L53

[Here is the next docs for this prop](https://nextjs.org/docs/api-reference/next/image#placeholder)

Keep up the good work ✨

**Comment by lorenzodejong** [comment]
This is fixed by [PR 41](https://github.com/bundlesandbatches/next-sanity-image/pull/41) and release in version 4.0.0!
