### ISSUE TITLE
Can't use `.height()` in `imageBuilder`

### ISSUE THREAD

**Issue by mitchuman** [bundlesandbatches/next-sanity-image#34]
Setting `.height(...)` in `options.imageBuilder` results in "stretched" images, even with `position: relative` set to a parent element, likely due to the `<Image/>` component from `next/image` not being able to handle explicit heights.

FYI: Use in conjunction with `.width(...)` (e.g. `.width(200).height(200)`) does get expected results — a 200x200 px image.

**Comment by lorenzodejong** [comment]
This is documented in the gotcha's (https://github.com/bundlesandbatches/next-sanity-image#gotchas). A uniform width/height should be returned which is also set on the image element. This is due to the nature of how responsive images work on the web.
