### ISSUE TITLE
Update to `@sanity/client` v3.x

### ISSUE THREAD

**Issue by mitchuman** [bundlesandbatches/next-sanity-image#35]
Update to `@sanity/client` v3.x, versus the current v2.11.0

**Comment by fevernova90** [comment]
Submitted a PR for this, but it may have to wait for the next major version before being merged (if semver is strictly followed).

@mitchuman I've published my own fork to npm registry (which have a version 3.1.0 as peerDeps) if you'd like to use it. I am using it in my own project, run `npm install @fevernova90/next-sanity-image` to get it.

Warning: Use it at your own risk, also put a note somewhere for your project to change back to the this origin repo/package once there's a new version has been released/merged.

**Comment by lorenzodejong** [comment]
This is fixed from [PR 36](https://github.com/bundlesandbatches/next-sanity-image/pull/36) and released in version 4.0.0!
