### ISSUE TITLE
Caching behaviour

### ISSUE THREAD

**Issue by klattiation** [bundlesandbatches/next-sanity-image#37]
It seems like the loader doesn't implement a caching behaviour like the default loader of Nextjs.
https://nextjs.org/docs/api-reference/next/image#caching-behavior

Do you consider adding something like that in the future? It would be great if users wouldn't fetch images directly from the Sanity CDN, but from the domain of my website.

**Comment by lorenzodejong** [comment]
Currently it doesn't seem like this is an option for custom loaders. If you come across any Next.js documentation on how to configure this for this library i'd be happy to hear!
