### ISSUE TITLE
Image with src has unused properties assigned. Please remove "width" and "height".

### ISSUE THREAD

**Issue by ollebergkvist** [bundlesandbatches/next-sanity-image#39]
Warning:
```
Image with src "https://cdn.sanity.io/images/blabla-667x500.jpg?q=75&fit=clip&auto=format" and "layout='fill'" has unused properties assigned. Please remove "width" and "height".
```

When using the plugin like this:
```
{coverImage && imageUrl && (
  <Image {...coverImageProps} alt={alt} layout="fill" objectFit="cover" />
)}
```

**Comment by Javi** [comment]
@ollebergkvist  How did you fix this? I see the same warning and can't figure it out.

**Comment by ollebergkvist** [comment]
@Javi 

Skip the spread syntax {...coverImageProps}

And do this instead:
src={coverImageProps.src}
loader={coverImageProps.loader}
 alt={alt}
layout="fill"
objectFit="cover"

That worked for me, let me know if it solves it for you.

**Comment by Javi** [comment]
Ohh of course, that makes a lot of sense, thank you for the tip!
