### ISSUE TITLE
Handle quality from Next

### ISSUE THREAD

**Issue by RyKilleen** [bundlesandbatches/next-sanity-image#4]
At the moment it appears the only values passed on to a custom `imageBuilder` is width and `originalImageDimensions`, but [Next/Image allows for setting quality](https://nextjs.org/docs/api-reference/next/image#quality) as well in a loader.

I know I'd find this valuable

**Comment by lorenzodejong** [comment]
Hi RyKilleen, thanks for sharing the proposal. I noticed that this was an oversight from my side. Adding the quality by default would however potentially cause a breaking change in existing usages.

I will add the functionality somewhere next week and release a 2.0 version of the library. If you want, you can also send in a PR so we can get this integrated

**Comment by lorenzodejong** [comment]
Sorry for the delay in the new release, this functionality is now available in the `2.0.0` version (which has just been released on npm). The documentation has been updated as well, i would be glad to hear if this solves your use case!

**Comment by RyKilleen** [comment]
Awesome, thank you for the update! Excited to check it out
