### ISSUE TITLE
React 18 support?

### ISSUE THREAD

**Issue by crumb1e** [bundlesandbatches/next-sanity-image#40]
Would be awesome to get this updated to React 18!

The package is currently on `^17.0.2` and preventing us from upgrading to `next@12.2.0`.

**Comment by lorenzodejong** [comment]
It seems like this library has no conflicts in the feature ranges `^17.0.0 || ^18.0.0`. I've upgraded the library to support React 18 (including Next ^12.0.0). Releasing version 4.1.0 as we speak.
