### ISSUE TITLE
How to use useNextSanityImage() when image might be undefined

### ISSUE THREAD

**Issue by eivindmjelde** [bundlesandbatches/next-sanity-image#43]
Hi!

I have a case where the sanity image asset might be undefined. I tried to get around this by setting `null` conditionally: 

```ts
const imgProps = useNextSanityImage(sanityClient, image ?? null)
```

But I then get the following TS error: `Type 'null' is not assignable to type 'SanityImageSource'`. 

Is there any workaround for this case?

**Comment by lorenzodejong** [comment]
I will look into improved type support in the next release. The current function overload only supports this scenario when providing an options object as third parameter (https://github.com/bundlesandbatches/next-sanity-image/blob/main/src/useNextSanityImage.ts#L120.

I will look into a solution based on generics to dynamically infer the return type.

**Comment by lorenzodejong** [comment]
Version 5.0.0 has just been released which includes increased type support. This will likely fix your issue.

Also note that support for blur up options has been dropped from this library in version 5.0.0. Check out the upgrade guide for more information https://github.com/bundlesandbatches/next-sanity-image#upgrading-from-4xx-to-5xx.
