### ISSUE TITLE
Placeholder blur not working with next/future/image 

### ISSUE THREAD

**Issue by mmxdr** [bundlesandbatches/next-sanity-image#44]
It's now [required](https://nextjs.org/docs/api-reference/next/future/image#placeholder) to use base64 image in next/future/image component for blur placeholder.
Old component still works as expected.

**Comment by lorenzodejong** [comment]
Will look into this for the next release. Sanity should have the possibility to return a base64 lqip by default (https://www.sanity.io/docs/image-metadata).

Also mentioned in #8 and #17

**Comment by lorenzodejong** [comment]
Support for blur up options has been dropped from this library in version 5.0.0. Check out the upgrade guide for more information https://github.com/bundlesandbatches/next-sanity-image#upgrading-from-4xx-to-5xx.
