### ISSUE TITLE
Image props do not include alt text

### ISSUE THREAD

**Issue by hsdonkin** [bundlesandbatches/next-sanity-image#45]
`imageProps` as returned by `useNextSanityImage()` do not include the alt text attribute when media asset includes alt text

![image](https://user-images.githubusercontent.com/49598076/197080918-67aee64c-8915-491a-8289-7f00d7e657fe.png)

![image](https://user-images.githubusercontent.com/49598076/197080789-79802a3b-3b83-4ae8-b6b7-c34c351c103d.png)

**Comment by hsdonkin** [comment]
Realized the media tool was a different sanity plugin and we need to roll our own alt text strategy 😵‍💫

**Comment by lorenzodejong** [comment]
No worries, hope you come to a nice solution @hsdonkin

**Comment by thartman94** [comment]
@hsdonkin did you ever find a solution for this?

**Comment by michaelburtonray** [comment]
There has to be a way for these two packages to play nicely. How can we get the alt text passed down? @hsdonkin @lorenzodejong
