### ISSUE TITLE
Setting fill property to true produces error (Next 13)

### ISSUE THREAD

**Issue by merly267** [bundlesandbatches/next-sanity-image#48]
Heya - I've just upgraded to Next 13, all seems good except for images that were previously using `layout=fill` which has been deprecated for the boolean [fill property](https://nextjs.org/docs/api-reference/next/image#fill). 

Setting `fill` to true results in an error: "Image ... has both "width" and "fill" properties. Only one should be used." Could next-sanity-image treat `fill` the same as `layout=fill` and omit the width and height properties please? Thanks!

**Comment by lorenzodejong** [comment]
There's an example in the documentation on how to correctly implement this behavior (https://github.com/bundlesandbatches/next-sanity-image#fill-layout). This hook always returns a width and height from the result, this hook does not (and can not) take the provided layout option from the component into account.

**Comment by merly267** [comment]
Oh thanks! Sorry, my bad, I had misunderstood that part
