### ISSUE TITLE
Responsive example not working

### ISSUE THREAD

**Issue by AidanRRR** [bundlesandbatches/next-sanity-image#51]
Whenever I add the `images` part to my `next.config.js`:
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: ["cdn.sanity.io"],
    loader: "custom",
  },
};

module.exports = nextConfig;

```

The following message pops up:

```
error - Error: Image with src "[object Object]" is missing "loader" prop.
Read more: https://nextjs.org/docs/messages/next-image-missing-loader
    at Image (webpack-internal:///./node_modules/next/dist/client/image.js:64:19)
}
null
```

Do I need some additional configuration somewhere?

**Comment by fernandolucchesi** [comment]
> Whenever I add the `images` part to my `next.config.js`:
> 
> ```
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   reactStrictMode: true,
>   swcMinify: true,
>   images: {
>     domains: ["cdn.sanity.io"],
>     loader: "custom",
>   },
> };
> 
> module.exports = nextConfig;
> ```
> 
> The following message pops up:
> 
> ```
> error - Error: Image with src "[object Object]" is missing "loader" prop.
> Read more: https://nextjs.org/docs/messages/next-image-missing-loader
>     at Image (webpack-internal:///./node_modules/next/dist/client/image.js:64:19)
> }
> null
> ```
> 
> Do I need some additional configuration somewhere?

Hi Aidan!

I run into the same issue on my project. The error is not related to the sanity image, but to another image you are using in your project where the URL is pointing to a public image for example. Deleting the `loader: "custom"` line made it work for both cases.

**Comment by AidanRRR** [comment]
@fernandolucchesi Oh, cool! Thanks for sharing.

**Comment by kerns** [comment]
Could the problem be that this is the Next.js 12 config format? I think v.13 wants something along the lines of...

```
images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.dummyimage.com',
      },
      {
        protocol: 'https',
        hostname: 'naver.github.io',
      },
      {
        protocol: 'https',
        hostname: 'placekitten.com',
      },
      {
        protocol: 'https',
        hostname: 'cdn.sanity.io',
      },
    ],
  },
```
