### ISSUE TITLE
Feature Request: Support LQIP?

### ISSUE THREAD

**Issue by RyKilleen** [bundlesandbatches/next-sanity-image#8]
Would there be any interest in adding a pre-load state that uses the LQIP metadata when provided? It seems like that'd be super useful, inspired by https://www.sanity.io/plugins/gatsby-plugin-sanity-image

**Comment by lorenzodejong** [comment]
There's actually some active development on blur up support from the Next.js side. There's been some experiments a couple of weeks ago on possible implementations: https://github.com/vercel/next.js/issues/18858.

Blur up functionality is not easily implemented from this library without creating a custom `Image` component. I would recommend to wait for a possible integration from the Next.js side (in the `next/image` component) before we attempt to implement this ourselves.

**Comment by RyKilleen** [comment]
Thanks for the head's up, that wasn't on my radar! I'll keep an eye over there and some fingers crossed, thanks!

**Comment by lorenzodejong** [comment]
Hey @RyKilleen just a heads-up that blur-up image support has been added in Next.js 11.0.0 which was released yesterday. I've integrated support for this in the library (version 3.1.0).

Check out #10

**Comment by RyKilleen** [comment]
Just wanted to follow up here and ask: is there an easy way to build in `lqip` support? It's a field built on to assets by default in sanity, and provides a base-64 without an additional request to the Sanity CDN

**Comment by lorenzodejong** [comment]
Ok great! I wasn't aware of the fact that there's a base 64 encoded version of the image already available. If you'd like you can work on a PR and i'll give it a review along the way! 👍

**Comment by RyKilleen** [comment]
Great! At a high-level, I think my approach will be to override any of the blurup types if the image metadata exists with a `lqip`. It'll be on users to include it in their query, and to provide the full image object instead of just a reference.

**Comment by lorenzodejong** [comment]
Sounds good, i think that approach should work. I've also mentioned issue #17 regarding placeholders for SVG images. Perhaps the `metadata` field already handles this behavior correctly when using SVG images. Might be worthwhile to try it out with this new implementation and see if this also fixes issue #17 .

**Comment by lorenzodejong** [comment]
Support for lqip placeholder has been dropped from this library in version 5.0.0. Check out the upgrade guide for more information https://github.com/bundlesandbatches/next-sanity-image#upgrading-from-4xx-to-5xx.
